"""Rebuild the review aggregation and results narrative solely from source JSONs.

No simulations, mutable timestamps, or scratchpad runner dependencies. --check
compares the generated bytes with the stored aggregate and narrative.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import subprocess
import sys

import numpy as np
from scipy.optimize import brentq
from scipy.stats import norm

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))
import pcso_mlx_sim as sim
from pcso_mlx_validate import BOUNDS, assert_paired

FOLDER = ROOT / 'results/exploratory'
AGGREGATE = FOLDER / 'pcso_mlx_null_calibration_2026-09-23.json'
DOC = ROOT / 'docs/RESULTS_PCSO_MLX_BACKEND_2026-09-23.md'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def screen_sensitivity(n=400, m=10000, p0=.005, alpha=.05, power=.8):
    critical = math.sqrt(-.5 * math.log(alpha / 2)) * math.sqrt(1/n + 1/m)
    # DKW + union bound: each empirical CDF stays within epsilon_i with
    # probability >= 1-(1-power)/2; their errors add under any alternative.
    sufficient = critical + sum(math.sqrt(math.log(4 / (1-power)) / (2*k)) for k in (n, m))
    zcrit, zpower = norm.ppf(1-alpha/2), norm.ppf(power)
    def equation(delta):
        p1 = p0 + delta
        pooled = (n*p0 + m*p1)/(n+m)
        return delta - zcrit*math.sqrt(pooled*(1-pooled)*(1/n+1/m)) - zpower*math.sqrt(p0*(1-p0)/n+p1*(1-p1)/m)
    fisher_delta = brentq(equation, 1e-12, .5)
    return {'alpha': alpha, 'target_power': power, 'cpu_n': n, 'mlx_n': m,
            'ks_rejection_D_approx': critical,
            'ks_80pct_power_sufficient_CDF_separation': sufficient,
            'ks_MDE_method': 'conservative sufficient separation via DKW union bound; not an exact minimum',
            'fisher_80pct_MDE_rate_difference_approx': fisher_delta,
            'fisher_reference_cpu_rate': p0,
            'fisher_implied_mlx_rate_approx': p0+fisher_delta,
            'fisher_MDE_method': 'two-proportion normal approximation; discrete Fisher power can differ, especially with 2 expected CPU events',
            'interpretation': 'gross screens cannot resolve arithmetic residuals; paired bounds are primary'}


def build():
    sources = {}
    def read(name):
        path = FOLDER / name
        sources[str(path.relative_to(ROOT))] = digest(path)
        return json.loads(path.read_text())
    matched, paired = {}, {}
    for name, m in [(n, 32) for n in sim.PORTED] + [('cp_nest', 128)]:
        key = f'{name}_m{m}'
        matched[key] = read(f'pcso_mlx_matched_{key}.json')
        paired[key] = read(f'pcso_mlx_paired_{key}.json')
        for artifact in (matched[key], paired[key]):
            assert artifact['_meta']['schedule_draws'] == 994
            for value in artifact['devices'].values():
                assert_paired(value['paired'])
                if artifact['drift_asserted']:
                    assert value['drift']['extrapolated_994_bound'] < 1e-4
    v0_distributions = {}
    for key, artifact in paired.items():
        if 'v0_final' in artifact['cpu']:
            v0_distributions[key] = {}
            for backend, values in [('cpu', artifact['cpu']), ('gpu', artifact['devices']['gpu']['values'])]:
                v = np.asarray(values['v0_final'])
                v0_distributions[key][backend] = {'mean': float(v.mean()), 'q50': float(np.quantile(v,.5)), 'q90': float(np.quantile(v,.9)), 'q99': float(np.quantile(v,.99)), 'fraction_ge_0_9': float((v >= .9).mean())}
    power, power_large = {}, {}
    for name in ('cp_nest', 'tilt_linear'):
        power[name] = read(f'pcso_mlx_power_{name}_m128.json')
        power_large[name] = read(f'pcso_mlx_power_{name}_mlx_2000.json')
        for artifact in (power[name], power_large[name]):
            assert artifact['theta1'] == .05 and artifact['_meta']['M'] == 128
            assert artifact['_meta']['schedule_draws'] == 994
        assert power[name]['n_streams'] == 200
        assert power_large[name]['models'][name]['n_streams'] == 2000
        for value in power[name]['devices'].values():
            assert_paired(value['paired'])
    screens, timings, summaries = {}, {}, {}
    benchmarks = []
    for name in sim.MODELS:
        jobs = {(b, n): read(f'pcso_mlx_bench_{name}_{b}_{n}.json')
                for b, n in [('cpu',400), ('mlx',400), ('mlx',10000)]}
        benchmarks.extend(jobs.values())
        cpu, gpu = jobs['cpu',400], jobs['mlx',10000]
        result = {k: np.asarray(gpu[k]) for k in ('sup', 'log_sr_max')}
        screens[name] = sim.compare_null(cpu['sup'], cpu['log_sr_max'], result)
        if name == 'uniform':
            screens[name]['analytic_reference'] = True
            screens[name]['max_abs_sr_roundoff'] = float(np.max(np.abs(np.asarray(cpu['log_sr_max'])[:,None]-result['log_sr_max'])))
            screens[name]['point_mass_note'] = ('Unrounded KS distinguishes disjoint point masses separated by host roundoff (~1e-15 nats); '
                'the old 5e-324 p-value measured that tie, not a model discrepancy. Raw point-mass KS removed; rounded SR is included in verdict.')
        timings[name] = {f'{b}{n}': job['wall_s'] for (b,n),job in jobs.items()}
        summaries[name] = gpu['summary']
    source_files = ['src/pcso_mlx_sim.py', 'src/pcso_mlx_benchmark.py', 'src/pcso_model_registry.py',
                    'tests/test_pcso_mlx_sim.py', 'tools/pcso_mlx_validate.py', 'tools/pcso_mlx_bench_all.py',
                    'tools/pcso_mlx_remote.py', 'tools/pcso_mlx_report.py', 'tools/snapshot_commitment.py']
    scripts = {p: digest(ROOT / p) for p in source_files}
    validation = [*matched.values(), *paired.values(), *power.values()]
    for artifact in [*validation, *power_large.values(), *benchmarks]:
        assert artifact['_meta']['schedule_draws'] == 994
        assert artifact['_meta']['schedule_sha256'] == '7ca585656595199a76a78c4834eed7aa1a0defa536df73c3f78351bd159db9cb'
        for path, sha in artifact['_meta']['source_sha256'].items():
            assert scripts[path] == sha, (path, 'stale source artifact')
    for artifact in validation:
        assert artifact['script_sha256'] == scripts['tools/pcso_mlx_validate.py'], 'stale validation script'
    for artifact in benchmarks:
        assert artifact['script_sha256'] == scripts['src/pcso_mlx_benchmark.py'], 'stale benchmark script'
    equivalence = read('pcso_mlx_equivalence_2026-09-23.json')
    cpu_without_mlx = read('pcso_mlx_cpu_without_mlx.json')
    assert cpu_without_mlx['_meta']['device'] == 'unavailable'
    assert cpu_without_mlx['_meta']['mlx_version'] is None
    assert cpu_without_mlx['script_sha256'] == scripts['src/pcso_mlx_benchmark.py']
    for path, sha in cpu_without_mlx['_meta']['source_sha256'].items():
        assert scripts[path] == sha
    registry_diff = subprocess.check_output(['git','diff','origin/master','--','src/pcso_model_registry.py'], cwd=ROOT, text=True)
    assert not registry_diff
    out = {'status': 'exploratory, not registered', 'base_sha': subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),
           'registry_diff_origin_master': registry_diff, 'schedule_cutoff': '2026-09-20',
           'schedule_note': 'New base has 999 draws; the requested 994-draw schedule is its exact prefix.',
           'ported': list(sim.PORTED), 'uniform': 'analytic reference (no GPU computation)', 'bounds': BOUNDS,
           'matched': matched, 'paired': paired, 'v0_distributions': v0_distributions,
           'power': power, 'power_mlx_2000': power_large, 'test_equivalence': equivalence,
           'cpu_without_mlx': cpu_without_mlx, 'gross_screens': screens,
           'screen_sensitivity': screen_sensitivity(), 'timing_s': timings, 'null_10000': summaries,
           'source_json_sha256': sources, 'script_sha256': scripts,
           'grid': 'not run; lead will pre-declare separately',
           'sampling_note': 'The 400-stream and 10000-stream benchmark artifacts are disjoint samples (different generator seeds); neither is a prefix of the other.',
           'issues': ['Float32 residual is device-dependent; equivalence bounds are empirical on the specified inputs, not a proof for all inputs.',
                      'Independent review CLI was unavailable in the prior round: pi --help reported EPERM creating its settings lock. It was not retried; this continuation received self-review only. No alternate permissions or credentials attempted.'],
           'ledger_note': 'snapshot_commitment.py hashes docs/RESULTS_*; the picker narrative appears in its snapshot-format blocks at ledger lines 1287/1349. results/ is excluded. Use the existing snapshot tool, never a hand-edited row.'}
    out['test_log_sha256'] = {}
    for host in ('local','m5'):
        path = FOLDER / f'pcso_mlx_tests_{host}_2026-09-23.log'
        out['tests_'+host] = path.read_text().strip().splitlines()[-1]
        out['test_log_sha256'][str(path.relative_to(ROOT))] = digest(path)
    text = json.dumps(out, indent=2, allow_nan=False) + '\n'
    return out, text


def narrative(out, sha):
    lines = ['# RESULTS — Exploratory MLX backend, fix round 1 (2026-09-23)', '',
        'Status: exploratory, not registered. All requested review findings are ACCEPT. Four ported models: '+', '.join(out['ported'])+'. Uniform is an analytic reference (no GPU computation).', '',
        'Source JSON: `results/exploratory/pcso_mlx_null_calibration_2026-09-23.json`; SHA-256 `'+sha+'`.',
        'Generator: `tools/pcso_mlx_report.py`; SHA-256 `'+out['script_sha256']['tools/pcso_mlx_report.py']+'`. The JSON includes every source-JSON and script hash.', '',
        'Base: `'+out['base_sha']+'`. The registered CPU source is unchanged. The new base has 999 draws; this review pins the requested 994-draw prefix through 2026-09-20, with schedule digest and pool counts in each artifact.', '',
        '```text', '$ git diff origin/master -- src/pcso_model_registry.py', '```', '(stdout empty; exit 0.)', '',
        'Primary validation uses the same cp_streams draws and float32-quantised Gaussians on the unchanged CPU models and MLX; the CPU casts those exact values back to float64. The measured residual excludes Gaussian input quantisation but includes all float32 arithmetic and device kernels. Host schedule constants and evidence/SR accumulation remain float64.', '',
        'Full-horizon matched checks use 16 streams per configuration on both MLX devices. Delta means MLX minus registered CPU. OLS fits cumulative delta per stream against t; the reported bound is max(|intercept| + 994|slope|), required <1e-4 nats; max per-draw error <=1e-5 and sup error <=1e-3.', '',
        '| Model / M | Device | max absolute delta le_t | Mean OLS slope | Max absolute slope | t=994 bound | Max sup error |',
        '|---|---|---:|---:|---:|---:|---:|']
    for key, artifact in out['matched'].items():
        for dev, v in artifact['devices'].items():
            d = v['drift']
            lines.append(f"| {key} | {dev} | {d['max_abs_delta_le_t']:.6g} | {d['mean_ols_slope_cumulative_delta_vs_t']:.6g} | {d['max_abs_ols_slope_cumulative_delta_vs_t']:.6g} | {d['extrapolated_994_bound']:.6g} | {v['paired']['sup']['max_abs']:.6g} |")
    lines += ['', 'Primary paired distribution: 400 full-horizon streams per configuration, GPU versus registered CPU. Bounds (mean absolute / q99 absolute / max absolute): sup and final log-evidence = 1e-4 / 3e-4 / 1e-3 nats; v_T(0) = 1e-5 / 3e-5 / 1e-4. Signed means and all stream values are also in JSON.', '',
              '| Model / M | Statistic | Mean absolute delta | q99 absolute delta | Max absolute delta |', '|---|---|---:|---:|---:|']
    for key, artifact in out['paired'].items():
        for stat, v in artifact['devices']['gpu']['paired'].items():
            lines.append(f"| {key} | {stat} | {v['mean_abs']:.6g} | {v['q99_abs']:.6g} | {v['max_abs']:.6g} |")
    lines += ['', 'Final level-zero weight distributions (400 streams):', '', '| Model / M | Backend | Mean | q50 | q90 | q99 | Fraction >=0.9 |', '|---|---|---:|---:|---:|---:|---:|']
    for key, devices in out['v0_distributions'].items():
        for dev,v in devices.items():
            lines.append(f"| {key} | {dev} | {v['mean']:.8g} | {v['q50']:.8g} | {v['q90']:.8g} | {v['q99']:.8g} | {v['fraction_ge_0_9']:.6g} |")
    lines += ['', 'Device comparison on identical matched inputs:', '', '| Model / M | max per-draw GPU minus MLX CPU | max final log-evidence difference |', '|---|---:|---:|']
    for key, artifact in out['matched'].items():
        v = artifact['gpu_minus_mlx_cpu']
        lines.append(f"| {key} | {v['le']['max_abs']:.6g} | {v['final_log_e']['max_abs']:.6g} |")
    lines += ['', 'The residual is not purely device-independent float32 rounding: the CPU and GPU kernels give different errors. Both devices must satisfy the same empirical bounds. CP-NEST uses a normalized ESP recurrence to avoid the rounded C(55,6) denominator and large-integer cancellation.', '',
              'Gross screens (M=32, 400 independent CPU versus 10000 MLX streams): KS at 1e-5-nat resolution for sup and SR, plus Fisher on crossings; the verdict includes all three p-values. Values below 0.10 receive a warning; below 0.05 indicate a discrepancy.', '',
              '| Model | sup KS p | SR KS p | Fisher p | CPU / MLX crossings | Verdict |', '|---|---:|---:|---:|---|---|']
    for key, v in out['gross_screens'].items():
        lines.append(f"| {key} | {v['ks_p']:.6g} | {v['sr_ks_p']:.6g} | {v['crossing_fisher_p']:.6g} | {v['cpu_crossings']} / {v['mlx_crossings']} | {v['verdict']} |")
    s = out['screen_sensitivity']
    lines += ['', f"KS critical D is approximately {s['ks_rejection_D_approx']:.6g}; a conservative sufficient CDF separation for 80% power is {s['ks_80pct_power_sufficient_CDF_separation']:.6g} (DKW union bound). Fisher's approximate 80%-power minimum detectable rate difference is {s['fisher_80pct_MDE_rate_difference_approx']:.6g}, assuming CPU rate 0.005; this is a normal approximation, and discrete exact power can differ substantially with only two expected CPU events. These screens cannot establish arithmetic equivalence.", '',
              out['gross_screens']['uniform']['point_mass_note'], '', out['sampling_note'], '',
              'POWER: theta1=0.05, M=128, 200 matched CPU/MLX streams (seed 20260927) plus 2000 independent MLX streams (seed 20260928), horizon 994, prior initialisation (not registered-window conditioning). Non-crossers are right-censored at 994; the censored median uses the full cohort, and an unreached median means >994 draws.', '',
              '| Model | Backend | Streams | Crossed | Fraction | Censored median | Horizon |', '|---|---|---:|---:|---:|---|---:|']
    for name, artifact in out['power'].items():
        for backend, v in [('CPU', artifact['cpu']['summary']), ('MLX GPU (matched)',artifact['devices']['gpu']['summary']),
                           ('MLX GPU (independent)',out['power_mlx_2000'][name]['models'][name])]:
            lines.append(f"| {name} | {backend} | {v['n_streams']} | {v['n_crossed']} | {v['fraction_crossed']:.6g} | {v['median_draws_to_cross_censored']} | {v['horizon']} |")
    lines += ['', 'POWER paired errors:', '', '| Model | Statistic | Mean absolute | q99 absolute | Max absolute |', '|---|---|---:|---:|---:|']
    for name, artifact in out['power'].items():
        for stat,v in artifact['devices']['gpu']['paired'].items():
            lines.append(f"| {name} | {stat} | {v['mean_abs']:.6g} | {v['q99_abs']:.6g} | {v['max_abs']:.6g} |")
    lines += ['', 'Timing in seconds (M5; CPU uses eight workers; includes sampling, worker startup/compilation and accumulation, excludes imports/serialization):', '',
              '| Model | CPU 400 | MLX 400 | MLX 10000 |', '|---|---:|---:|---:|']
    for key,v in out['timing_s'].items():
        lines.append(f"| {key} | {v['cpu400']:.3f} | {v['mlx400']:.3f} | {v['mlx10000']:.3f} |")
    lines += ['', 'Verification: local '+out['tests_local']+'; M5 '+out['tests_m5']+'.', '',
              'Every M5 command, including rsync, runs under the repository Python supervisor with a <=300-second deadline and process-group cleanup. Cleanup evidence is in `results/exploratory/pcso_mlx_m5_leftovers_2026-09-23.log`.', '',
              'Reproduction (each M5 job is separately bounded; --check regenerates aggregate/narrative bytes from saved JSON, while raw rerun timings naturally vary):', '', '```sh',
              'python tools/pcso_mlx_remote.py sync',
              'python tools/pcso_mlx_bench_all.py matched', 'python tools/pcso_mlx_bench_all.py paired',
              'python tools/pcso_mlx_bench_all.py power', 'python tools/pcso_mlx_bench_all.py bench',
              'python tools/pcso_mlx_bench_all.py tests',
              'python tools/pcso_mlx_remote.py pull',
              'python -m pytest tests/ -q -p no:cacheprovider > results/exploratory/pcso_mlx_tests_local_2026-09-23.log',
              'python src/pcso_mlx_benchmark.py --model cp_nest --backend cpu --streams 2 --workers 1 --max-draws 4 --out results/exploratory/pcso_mlx_cpu_without_mlx.json',
              'python tools/pcso_mlx_remote.py leftovers > results/exploratory/pcso_mlx_m5_leftovers_2026-09-23.log', 'python tools/pcso_mlx_report.py',
              'python tools/pcso_mlx_report.py --check', '```', '',
              out['ledger_note'], '', 'Sensitivity grid: **not run**; the lead will pre-declare it separately. Dirichlet and ensemble remain CPU-only.', '',
              'Limitations: '+ ' '.join(out['issues']), '', 'Script hashes:', '', '| Path | SHA-256 |', '|---|---|']
    for path, h in out['script_sha256'].items():
        lines.append(f'| `{path}` | `{h}` |')
    lines += ['', 'Source JSON hashes:', '', '| Path | SHA-256 |', '|---|---|']
    for path,h in out['source_json_sha256'].items():
        lines.append(f'| `{path}` | `{h}` |')
    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    out, text = build()
    doc = narrative(out, hashlib.sha256(text.encode()).hexdigest())
    superseded = ('# Superseded MLX report\n\nThe previous narrative and aggregate are superseded by '
        '`docs/RESULTS_PCSO_MLX_BACKEND_2026-09-23.md` and the regenerated '
        '`pcso_mlx_null_calibration_2026-09-23.json`.\n\nOnly source JSONs listed in the new aggregate hash manifest '
        'are current evidence. Other legacy logs/probes and `.pi/mlx_finish/` outputs are historical and must not be used as final evidence.\n')
    for path, content in [(AGGREGATE,text),(DOC,doc),(FOLDER / 'pcso_mlx_report_2026-09-23.md',superseded)]:
        if args.check:
            assert path.read_bytes() == content.encode(), f'{path}: regeneration differs'
        else:
            path.write_text(content)
    print('byte-identical aggregation and narrative' if args.check else f'wrote {AGGREGATE} and {DOC}')


if __name__ == '__main__':
    main()
